version: '3.1'

services:

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8000:8080
    links: 
      - db
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.6
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress
    container_name: wordpress 
    depends_on:
      - db
    ports:
      - "8088:80"
    volumes:
      - ./volumes/wordpress/theme:/var/www/html/wp-content/themes/theme_name
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins
      - ./volumes/wordpress/uploads:/var/www/html/wp-content/uploads
    links: 
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress