version: '3.1'

services:

  adminer:
    container_name: adminer
    image: adminer
    links: 
      - db
    depends_on:
      - db
    ports:
      - 8000:8080

  db:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - db
    links: 
      - db
    ports:
      - "80:80"
    volumes:
      - ./volumes/wordpress/theme:/var/www/html/wp-content/themes/theme_name
      - ./volumes/wordpress/plugins:/var/www/html/wp-content/plugins
      - ./volumes/wordpress/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress

  matomo:
    container_name: matomo
    image: matomo
    depends_on:
      - db
    links: 
      - db
    ports:
      - "8080:80"
    volumes:
    - ./volumes/matomo/config:/var/www/html/config:rw
    - ./volumes/matomo/logs:/var/www/html/logs